module NammaAP.DB.Connection
  ( mkDBEnv,
    runDB,
    withConn,
    ensureSchema,
  )
where

import Control.Monad.IO.Class (MonadIO (liftIO))
import Data.Pool (createPool, withResource)
import Database.Beam.Postgres (Pg, runBeamPostgres)
import Database.PostgreSQL.Simple (Connection, close, connectPostgreSQL, execute_)
import qualified Data.ByteString.Char8 as BS
import NammaAP.Config (Config (..))
import NammaAP.Environment (DBEnv (..))

mkDBEnv :: Config -> IO DBEnv
mkDBEnv cfg = do
  pool <- createPool (connectPostgreSQL (mkConnString cfg)) close 1 60 10
  let db = DBEnv pool
  ensureSchema db
  pure db

runDB :: DBEnv -> Pg a -> IO a
runDB db action = withConn db (\conn -> runBeamPostgres conn action)

withConn :: DBEnv -> (Connection -> IO a) -> IO a
withConn DBEnv {..} = withResource dbPool

mkConnString :: Config -> BS.ByteString
mkConnString Config {..} =
  case databaseUrl of
    Just url -> BS.pack url
    Nothing ->
      BS.pack $
        "host=" <> postgresHost
          <> " port=" <> show postgresPort
          <> " user=" <> postgresUser
          <> " password=" <> postgresPassword
          <> " dbname=" <> postgresDatabase

ensureSchema :: DBEnv -> IO ()
ensureSchema db = withConn db $ \conn -> do
  _ <- execute_ conn "CREATE TABLE IF NOT EXISTS product_config (id serial primary key, product text not null, repo_name text not null, product_type text not null, product_acronym text not null, release_branch text not null, need_infra_approval boolean null, target_config text null)"
  _ <- execute_ conn "CREATE TABLE IF NOT EXISTS release_config (id serial primary key, emails text null, rollout_strategy text null, decision_config text null, service text not null, product text not null, flags text null, slack_webhook_urls text null, service_acronym text null, service_type text null, bitbucket_path text null, revert_strategy text null, target_config text null)"
  _ <- execute_ conn "CREATE TABLE IF NOT EXISTS server_config (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type varchar(255) not null default '', name varchar(255) not null, value text not null default '', last_updated timestamp without time zone not null default CURRENT_TIMESTAMP, enabled int not null default 1)"
  _ <- execute_ conn "CREATE TABLE IF NOT EXISTS release_tracker (id text primary key, status text not null, description text null, new_version text not null, old_version text not null, product text not null, service text not null, mode text null, date_created timestamptz not null, last_updated timestamptz not null, start_time timestamptz null, end_time timestamptz null, release_manager text not null, approved_by text null, env text not null, priority int not null, rollout_strategy text null, rollout_history text null, schedule_time timestamptz null, release_tag text not null, events text null, change_log text null, release_context text null, info text null, udf1 text null, udf2 text null, udf3 text null, is_approved boolean null, is_infra_approved boolean null, metadata text null, category text null, release_wf_status text null, global_id text null, new_service boolean null, is_art_recorder int null, cronjob_suspend boolean null, ab_hs_status text null default 'Uninitiated')"
  -- Migrate legacy column names if they exist
  _ <- execute_ conn "DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='release_tracker' AND column_name='tracker_type') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='release_tracker' AND column_name='category') THEN ALTER TABLE release_tracker RENAME COLUMN tracker_type TO category; END IF; END $$"
  _ <- execute_ conn "DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='release_tracker' AND column_name='workflow_status') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='release_tracker' AND column_name='release_wf_status') THEN ALTER TABLE release_tracker RENAME COLUMN workflow_status TO release_wf_status; END IF; END $$"
  _ <- execute_ conn "ALTER TABLE release_tracker ADD COLUMN IF NOT EXISTS approved_by text null"
  _ <- execute_ conn "ALTER TABLE release_tracker ADD COLUMN IF NOT EXISTS global_id text null"
  _ <- execute_ conn "ALTER TABLE release_tracker ADD COLUMN IF NOT EXISTS new_service boolean null"
  _ <- execute_ conn "ALTER TABLE release_tracker ADD COLUMN IF NOT EXISTS is_art_recorder int null"
  _ <- execute_ conn "ALTER TABLE release_tracker ADD COLUMN IF NOT EXISTS cronjob_suspend boolean null"
  _ <- execute_ conn "ALTER TABLE release_tracker ADD COLUMN IF NOT EXISTS ab_hs_status text null default 'Uninitiated'"
  _ <- execute_ conn "DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='release_tracker' AND column_name='is_art_recorder' AND data_type='boolean') THEN ALTER TABLE release_tracker ALTER COLUMN is_art_recorder TYPE int USING CASE WHEN is_art_recorder THEN 1 ELSE 0 END; END IF; END $$"
  _ <- execute_ conn "CREATE TABLE IF NOT EXISTS release_events (re_id serial primary key, re_release_id text not null, re_category text not null, re_label text not null, re_payload jsonb not null, re_created_at timestamptz not null)"
  -- Migrate product_config: pack K8s columns into target_config, then drop old columns
  _ <- execute_ conn "ALTER TABLE product_config ADD COLUMN IF NOT EXISTS target_config text"
  _ <- execute_ conn "DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='product_config' AND column_name='cluster') THEN UPDATE product_config SET target_config = json_build_object('cluster', COALESCE(cluster, ''), 'namespace', COALESCE(namespace, ''), 'vsName', COALESCE(vs_name, ''), 'kubeContext', kube_context, 'syncCluster', sync_cluster, 'vsLockedBy', vs_locked_by, 'vsLockTimestamp', vs_lock_timestamp)::text WHERE target_config IS NULL; ALTER TABLE product_config DROP COLUMN cluster, DROP COLUMN namespace, DROP COLUMN vs_name, DROP COLUMN sync_cluster, DROP COLUMN vs_locked_by, DROP COLUMN vs_lock_timestamp, DROP COLUMN kube_context; END IF; END $$"
  -- Migrate release_config: pack service_host into target_config, then drop old column
  _ <- execute_ conn "ALTER TABLE release_config ADD COLUMN IF NOT EXISTS target_config text"
  _ <- execute_ conn "DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='release_config' AND column_name='service_host') THEN UPDATE release_config SET target_config = json_build_object('serviceHost', service_host)::text WHERE target_config IS NULL; ALTER TABLE release_config DROP COLUMN service_host; END IF; END $$"
  pure ()
