-- Local test data — TEST_AUTOPILOT app group + services for end-to-end testing.
-- Idempotent: safe to re-run on every nix run .#dev startup.
--
-- Mirrors the K8s setup in namespace `test-autopilot`:
--   VirtualService: test-vs (routes /svc1 → test-svc, /svc2 → test-svc-2)
--   Deployments:    test-svc-v<N>, test-svc-2-v<N>
--   ConfigMap:      test-config (used by ConfigMap release tests)
--
-- Slack channel `oogway-test` is used by all release/configmap notifications.

-- ============================================================
-- Test app group (product-level row, service IS NULL)
-- ============================================================
INSERT INTO deployment_config (
  app_group, service, cluster, namespace, vs_name,
  product_acronym, product_type, need_infra_approval, slack_channel
)
SELECT 'TEST_AUTOPILOT', NULL, 'test-cluster', 'test-autopilot', 'test-vs',
       'TST', 'BackendService', false, 'oogway-test'
WHERE NOT EXISTS (
  SELECT 1 FROM deployment_config
  WHERE app_group = 'TEST_AUTOPILOT' AND service IS NULL
);

-- ============================================================
-- Test services (service-level rows)
-- ============================================================
INSERT INTO deployment_config (
  app_group, service, service_host, service_type, slack_channel
)
SELECT 'TEST_AUTOPILOT', 'TEST_SVC', 'test-svc', 'SERVICE', 'oogway-test'
WHERE NOT EXISTS (
  SELECT 1 FROM deployment_config
  WHERE app_group = 'TEST_AUTOPILOT' AND service = 'TEST_SVC'
);

INSERT INTO deployment_config (
  app_group, service, service_host, service_type, slack_channel
)
SELECT 'TEST_AUTOPILOT', 'TEST_SVC_2', 'test-svc-2', 'SERVICE', 'oogway-test'
WHERE NOT EXISTS (
  SELECT 1 FROM deployment_config
  WHERE app_group = 'TEST_AUTOPILOT' AND service = 'TEST_SVC_2'
);

-- ============================================================
-- Local-dev server_config tuning (faster polling, fast scale-down)
-- id is `generated by default as identity` — let Postgres assign it.
-- Idempotency via the literal-row + WHERE NOT EXISTS pattern.
-- ============================================================

-- Sync the identity sequence past any rows inserted with manual ids by
-- earlier migrations (a one-time fix for legacy DBs).
SELECT setval(
  pg_get_serial_sequence('server_config', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 0) FROM server_config), 1)
);

-- Faster runner poll for snappier dev feedback (default 20s → 10s)
INSERT INTO server_config (type, name, value, enabled, product)
SELECT 'INT', 'release_watch_delay', '10', 1, 'autopilot'
WHERE NOT EXISTS (SELECT 1 FROM server_config WHERE name = 'release_watch_delay');

-- Enable Slack notifications by default in local dev
INSERT INTO server_config (type, name, value, enabled, product)
SELECT 'BOOL', 'slack_enabled', 'true', 1, 'autopilot'
WHERE NOT EXISTS (SELECT 1 FROM server_config WHERE name = 'slack_enabled');

-- Fast scale-down delay (~36s) so old deployments shrink quickly during testing
INSERT INTO server_config (type, name, value, enabled, product)
SELECT 'FLOAT', 'pods_scale_down_delay_config', '0.01', 1, 'autopilot'
WHERE NOT EXISTS (SELECT 1 FROM server_config WHERE name = 'pods_scale_down_delay_config');
