-- System Control Centre — Combined Schema + Seed
-- This file is the canonical source for local development.
-- Safe to run multiple times (IF NOT EXISTS / ON CONFLICT).

-- ============================================================
-- Extensions
-- ============================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- Autopilot tables — release orchestration
-- ============================================================

-- Unified product+service deployment config
-- Product-level rows: service IS NULL (cluster, namespace, vs settings)
-- Service-level rows: service IS NOT NULL (rollout, slack, host settings)
CREATE TABLE IF NOT EXISTS deployment_config (
  id SERIAL PRIMARY KEY,
  app_group TEXT NOT NULL,
  service TEXT,
  cluster TEXT,
  namespace TEXT,
  vs_name TEXT,
  product_acronym TEXT,
  product_type TEXT,
  sync_cluster TEXT,
  need_infra_approval BOOLEAN,
  vs_locked_by TEXT,
  vs_lock_timestamp TIMESTAMPTZ,
  service_host TEXT,
  service_type TEXT,
  rollout_strategy TEXT,
  revert_strategy TEXT,
  decision_config TEXT,
  slack_channel TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_deployment_config
  ON deployment_config (app_group, COALESCE(service, ''));

CREATE TABLE IF NOT EXISTS release_tracker (
  id TEXT NOT NULL PRIMARY KEY,
  status TEXT NOT NULL,
  description TEXT,
  new_version TEXT NOT NULL,
  old_version TEXT NOT NULL,
  app_group TEXT NOT NULL,
  service TEXT NOT NULL,
  mode TEXT,
  date_created TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_updated TIMESTAMPTZ NOT NULL DEFAULT now(),
  start_time TIMESTAMPTZ,
  end_time TIMESTAMPTZ,
  release_manager TEXT NOT NULL,
  approved_by TEXT,
  env TEXT NOT NULL,
  priority INTEGER NOT NULL,
  rollout_strategy TEXT,
  rollout_history TEXT,
  schedule_time TIMESTAMPTZ,
  release_tag TEXT NOT NULL,
  change_log TEXT,
  release_context TEXT,
  info TEXT,
  sync_enabled TEXT,
  env_override_data TEXT,
  slack_thread_ts TEXT,
  is_approved BOOLEAN,
  is_infra_approved BOOLEAN,
  metadata TEXT,
  category TEXT DEFAULT 'BackendService',
  release_wf_status TEXT DEFAULT 'Init',
  global_id TEXT,
  new_service BOOLEAN,
  cronjob_suspend BOOLEAN,
  ab_hs_status TEXT DEFAULT 'Uninitiated'
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_release_tracker_global_id
  ON release_tracker (global_id) WHERE global_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS release_events (
  re_id SERIAL PRIMARY KEY,
  re_release_id TEXT NOT NULL,
  re_category TEXT NOT NULL,
  re_label TEXT NOT NULL,
  re_payload JSONB NOT NULL,
  re_created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS server_config (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR(255) NOT NULL DEFAULT '',
  name VARCHAR(255) NOT NULL,
  value TEXT NOT NULL DEFAULT '',
  last_updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enabled INTEGER NOT NULL DEFAULT 1,
  product TEXT
);

-- ============================================================
-- RBAC tables
-- Products and permissions are derived from Haskell ADTs, NOT stored in DB.
-- Only user/role/access/override data is stored here.
-- ============================================================

CREATE TABLE IF NOT EXISTS sc_person (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT NOT NULL UNIQUE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    is_superadmin BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sc_role (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_slug TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    is_system_role BOOLEAN NOT NULL DEFAULT false,
    permissions TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (product_slug, name)
);

CREATE TABLE IF NOT EXISTS sc_person_product_access (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id UUID NOT NULL REFERENCES sc_person(id) ON DELETE CASCADE,
    product_slug TEXT NOT NULL,
    role_id UUID NOT NULL REFERENCES sc_role(id),
    granted_by UUID REFERENCES sc_person(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (person_id, product_slug)
);

CREATE TABLE IF NOT EXISTS sc_person_permission_override (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id UUID NOT NULL REFERENCES sc_person(id) ON DELETE CASCADE,
    product_slug TEXT NOT NULL,
    permission_action TEXT NOT NULL,
    override_type TEXT NOT NULL CHECK (override_type IN ('GRANT', 'DENY')),
    granted_by UUID REFERENCES sc_person(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (person_id, product_slug, permission_action)
);

CREATE TABLE IF NOT EXISTS sc_registration_token (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id UUID NOT NULL REFERENCES sc_person(id) ON DELETE CASCADE,
    token TEXT NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS sc_audit_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id UUID REFERENCES sc_person(id),
    action TEXT NOT NULL,
    entity_type TEXT,
    entity_id TEXT,
    details JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Seed data
-- ============================================================

-- Superadmin user (password: admin123)
INSERT INTO sc_person (email, first_name, last_name, password_hash, is_superadmin)
VALUES ('admin@juspay.in', 'Admin', 'User', 'admin123', true)
ON CONFLICT (email) DO NOTHING;

-- System roles for Autopilot product
INSERT INTO sc_role (product_slug, name, description, is_system_role) VALUES
  ('autopilot', 'Admin', 'Full access to all Autopilot features', true),
  ('autopilot', 'Manager', 'Can create, approve, manage releases (no config edit)', true),
  ('autopilot', 'Viewer', 'Read-only access to Autopilot', true)
ON CONFLICT (product_slug, name) DO NOTHING;

-- System roles for Config Manager product
INSERT INTO sc_role (product_slug, name, description, is_system_role) VALUES
  ('config-manager', 'Admin', 'Full access to Config Manager', true),
  ('config-manager', 'Manager', 'Can create and apply configs', true),
  ('config-manager', 'Viewer', 'Read-only access to Config Manager', true)
ON CONFLICT (product_slug, name) DO NOTHING;

-- Assign superadmin to Admin role on both products
INSERT INTO sc_person_product_access (person_id, product_slug, role_id)
SELECT p.id, 'autopilot', r.id
FROM sc_person p, sc_role r
WHERE p.email = 'admin@juspay.in' AND r.product_slug = 'autopilot' AND r.name = 'Admin'
ON CONFLICT (person_id, product_slug) DO NOTHING;

INSERT INTO sc_person_product_access (person_id, product_slug, role_id)
SELECT p.id, 'config-manager', r.id
FROM sc_person p, sc_role r
WHERE p.email = 'admin@juspay.in' AND r.product_slug = 'config-manager' AND r.name = 'Admin'
ON CONFLICT (person_id, product_slug) DO NOTHING;
